# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build with Maven
      run: mvn -Dmaven.test.skip=true -B package --file pom.xml
    
    - name: copy jar to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: target/missionboard-0.0.1-SNAPSHOT.jar
        remote: ~/java_apps/missionboard-0.0.1-SNAPSHOT.jar 
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
    
    - name: ssh-run-application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd ~/java_apps
          java -jar java_apps/missionboard-0.0.1-SNAPSHOT.jar


